### ISSUE TITLE
1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticDrilldown#28] opened 2023-01-21 09:54 UTC
https://phabricator.wikimedia.org/T178142

**Comment by krabina** [comment] 2024-05-03 18:29
Since this is reported for MW 1.27, I am closing is. If you can reproduce on 1.35 or 1.39, please reopen.

**Closed by krabina** 2024-05-03 18:29 UTC
Labels: bug
