### ISSUE TITLE
Special:BrowseData does not display data if "display parameters" are not provided (or #drilldowninfo is not called)

### ISSUE THREAD

**Issue by pastakhov** [SemanticMediaWiki/SemanticDrilldown#53] opened 2023-03-06 17:34 UTC
For example https://www.verwaltungskooperation.at/index.php?title=Spezial:Daten_durchsuchen/Aktuelles and any other tab where `display parameters` is not defined in the #drilldowninfo parser function.

Fixed in https://github.com/SemanticMediaWiki/SemanticDrilldown/pull/52

Deployed on https://wikirouge.net/texts/en/Special:BrowseData/Author

**Comment by krabina** [comment] 2024-05-03 14:54
Duplicate of #42

**Closed by krabina** 2024-05-03 14:54 UTC
